trying again

diff --git a/.github/workflows/test_action.yml b/.github/workflows/test_action.yml
--- a/.github/workflows/test_action.yml
+++ b/.github/workflows/test_action.yml
@@ -34,8 +34,15 @@ jobs:
 
       - name: Run pylint and handle exit code
         run: |
-          pylint --errors-only  *.py $(git ls-files '*.py') || echo "Pylint exited with errors, but continuing workflow."
-          
+          pylint --errors-only $(git ls-files '*.py')
+          pylint_exit=$?
+          if [ $pylint_exit -eq 0 ]; then
+            echo "Pylint exited with code $pylint_exit"
+          else
+            echo "Pylint exited with code $pylint_exit"
+            exit 1  # Fail the workflow if pylint finds issues
+          fi
+                  
       - name: Set up environment variables
         env:
           DB_USERNAME: ${{ secrets.DB_USERNAME }}
